#
# Copyright (c) 2006-2015 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        osprey_wifi_sms_injection_exploit:
            enable: true
            category: "Exploits"
            name: "Osprey_wifi_sms_injection_exploit"
            description: "Osprey_wifi_sms_injection_exploit"
            authors: ["@n0x00"]
            target:
                unknown: ["Osprey_wifi_hotspot"]
